version: '3.3'
services:
    outlook_events:
        build:
            context: .
        container_name: outlook_events
        restart: unless-stopped
        ports:
          - "8000:8000"
        volumes:
          - "./config.toml:/app/config.toml"
          - "~/.cache/outlookEvents:/cache"

